{% set name = "pandaboxlib" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MaxIV-KitsControls/lib-maxiv-pandaboxlib/archive/{{ version }}.tar.gz
  sha256: 37558ce9b01a5ad9204f7de1824ea333594ff0e6fb1f84d8400182fe8e98ac3d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}

test:
  imports:
    - pandaboxlib
  commands:
    - pip check
    - python -m pandaboxlib.version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MaxIV-KitsControls/lib-maxiv-pandaboxlib
  summary: Library to communicate with PandABox hardware
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marcoleorato
    - beenje
